version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - dupl
    - goconst
    - nakedret
    - prealloc
    - gosec
    - nolintlint # Checks for correct nolint usage
    - makezero # Checks for zero value initializations that can be simplified
    - wastedassign # Checks for assignments where the assigned value is not used
    - contextcheck # Checks for proper use of context values
    - durationcheck # Checks for time.Duration comparisons
    - forbidigo # Forbids specific function/method calls
    - funlen # Checks for excessive function length
    - gochecknoglobals # Checks for global variables
    - gocognit # Checks for excessive cognitive complexity
    - gocyclo # Checks for excessive cyclomatic complexity
    - err113 # Checks for wrapping errors consistently
    - mnd # Finds magic numbers
    - importas # Enforces consistent import aliases
    - lll # Checks for long lines
    - noctx # Checks for unwanted context usage
    - nolintlint # Checks for correct nolint usage
    - paralleltest # Checks for correct usage of t.Parallel() in tests
    - revive # Configurable, extensible linter for Go
    - copyloopvar # Checks for potential issues with variable shadowing
    - sqlclosecheck # Checks for missing sql.Close() calls
    - unused # Finds unused struct fields
    - thelper # Checks for test helpers that don't follow conventions
    - tparallel # Checks for parallel testing issues
    - unparam # Finds unused function parameters
    - sloglint

  settings:
    gocyclo:
      min-complexity: 20 # Set a threshold for cyclomatic complexity

    funlen:
      lines: 80 # Set a threshold for function length
      statements: 50 # Set a threshold for number of statements

    goconst:
      min-len: 3 # Set a threshold for minimum constant length

    lll:
      line-length: 120 # Set a threshold for line length

    dupl:
      threshold: 150 # Adjust threshold for code duplication detection

    misspell:
      locale: "US" # Use US English dictionary

    sloglint:
      no-mixed-args: false
      # Enforce using static values for log messages.
      # Default: false
      static-msg: true
      # Enforce a single key naming convention.
      # Values: snake, kebab, camel, pascal
      # Default: ""
      key-naming-case: snake

issues:
  max-issues-per-linter: 0 # Report all issues per linter
  max-same-issues: 0 # Report all instances of the same issue
